buildscript {\n    ext.kotlin_version = '1.9.0'\n    repositories {\n        google()\n        mavenCentral()\n    }\n\n    dependencies {\n        classpath 'com.android.tools.build:gradle:8.1.0'\n        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"\n        classpath 'com.google.gms:google-services:4.4.0'\n        classpath 'com.google.firebase:firebase-crashlytics-gradle:2.9.9'\n    }\n}\n\nallprojects {\n    repositories {\n        google()\n        mavenCentral()\n    }\n}\n\nrootProject.buildDir = '../build'\nsubprojects {\n    project.buildDir = "${rootProject.buildDir}/${project.name}"\n}\nsubprojects {\n    project.evaluationDependsOn(':app')\n}\n\ntasks.register("clean", Delete) {\n    delete rootProject.buildDir\n}\n